<?php

namespace App\Services\Screens;

use App\Models\User;
use App\Models\GameApp;
use App\Services\UI\UIBuilder;
use App\Services\GameInstanceService;
use App\Services\UI\Enums\LayoutType;

class GameLobbyScreenService
{
    private GameInstanceService $gameInstanceService;

    public function __construct(
        GameInstanceService $gameInstanceService
    ) {
        $this->gameInstanceService = $gameInstanceService;
    }

    /**
     * Get the game lobby screen data for a user and game app
     *
     * @param User $user
     * @param GameApp $gameApp
     * @return array
     */
    public function getGameLobbyScreen(User $user, GameApp $gameApp): array
    {
        $savedGames = $this->gameInstanceService->getSavedGames($user, $gameApp);
        $saved_games = $this->gameInstanceService->toApiFormat($savedGames);
        $canCreateNewGame = $this->gameInstanceService->canCreateNewGame($user, $gameApp);
        $maxInstances = $gameApp->max_instances_per_user;

        $container = UIBuilder::container()
            ->parent('canvas')
            ->layout(LayoutType::VERTICAL)
            ->title(t('games.game_lobby_title', ['name' => $gameApp->name]));

        // Build and add UI elements to the container using the tree structure
        $this->buildUIElements($container, $canCreateNewGame, $maxInstances, $saved_games);

        return $container->toJson();
    }

    /**
     * Build and add UI elements to the container
     * 
     * @param \App\Services\UI\Components\UIContainer $container The container to add elements to
     * @param bool $canCreateNewGame Whether user can create a new game
     * @param int $maxInstances Maximum instances per user
     * @param array $saved_games Array of saved games
     * @return void
     */
    private function buildUIElements($container, bool $canCreateNewGame, int $maxInstances, array $saved_games): void
    {
        $container->add(
            UIBuilder::button()
                ->label(t('new_game_button_label'))
                ->action('create_new_game')
                ->icon('plus')
                ->style('primary')
                ->variant('filled')
                ->enabled($canCreateNewGame)
                ->tooltip($canCreateNewGame ? t('new_game_button_tooltip') : t('cannot_create_new_game'))
        );

        // Warning Message (only if needed)
        $container->add(
            UIBuilder::label()
                ->text(t('instances_limit_reached', ['max' => $maxInstances]))
                ->style('warning')
                ->visible(!$canCreateNewGame)
        );

        // Saved Games Table
        // $container->add(
        //     $this->buildSavedGamesTable($saved_games, $maxInstances)
        // );
    }

    /**
     * Build the saved games table
     * 
     * @param array $saved_games Array of saved games
     * @param int $maxInstances Maximum instances per user
     * @return \App\Services\UI\Components\TableBuilder The table component
     */
    // private function buildSavedGamesTable(array $saved_games, int $maxInstances)
    // {
    //     $table = UIBuilder::table()
    //         ->title(count($saved_games) > 0 ? t('games.saved_games_title') : t('no_saved_games_title'))
    //         ->minRows($maxInstances); // Auto-fill will handle empty rows

    //     // Create header row with cells
    //     $headerRow = $table->createHeaderRow();
    //     $headerRow->createCell()->text(t('games.saved_game_number_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_name_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_state_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_role_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_status_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_join_method_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_last_played_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_play_column'));
    //     $headerRow->createCell()->text(t('games.saved_game_delete_column'));

    //     // Add rows using the new TableRow components
    //     $this->addTableRows($table, $saved_games);

    //     return $table;
    // }

    /**
     * Add rows to the table using TableRow components
     * Table will auto-fill empty rows based on minRows setting
     * 
     * @param \App\Services\UI\Components\TableBuilder $table The table to add rows to
     * @param array $saved_games Array of saved games
     * @return void
     */
    // private function addTableRows($table, array $saved_games): void
    // {
    //     $gameNumber = 1;

    //     // Add rows with saved games
    //     // Empty rows will be auto-generated by TableBuilder based on minRows
    //     // Note: createRow() now automatically adds the row to the table
    //     foreach ($saved_games as $game) {
    //         $this->buildGameRow($table, $game, $gameNumber++);
    //     }
    // }

    /**
     * Build a row for a saved game
     * 
     * @param \App\Services\UI\Components\TableBuilder $table The parent table
     * @param array $game Game data
     * @param int $gameNumber Row number
     * @return \App\Services\UI\Components\TableRowBuilder Row component
     */
    // private function buildGameRow($table, array $game, int $gameNumber)
    // {
    //     $savedGameId = $game['id'] ?? null;

    //     $playButton = $this->buildPlayButton($savedGameId);
    //     $deleteButton = $this->buildDeleteButton($savedGameId);

    //     // Create a TableRow component
    //     // Use cells() which will auto-generate TableCellBuilder components
    //     // For the last cell, we pass the container's built JSON as raw data
    //     $row = $table->createRow("saved_game_{$savedGameId}_row");
    //     $row->cells([
    //         $gameNumber,
    //         $game['name'] ?? t('games.default_game_name'),
    //         $game['state'],
    //         $game['game_user']['role'],
    //         $game['game_user']['status'],
    //         $game['game_user']['join_method'],
    //         $game['game_user']['last_played_at_human'],
    //         $playButton,
    //         $deleteButton,
    //     ]);
        
    //     return $row;
    // }

    /**
     * Build a play button for a game
     * 
     * @param int $gameId Game ID
     * @return \App\Services\UI\Components\ButtonBuilder Button component
     */
    // private function buildPlayButton(int $gameId)
    // {
    //     return UIBuilder::button("play_{$gameId}_game")
    //         ->label(t('games.play_game_action'))
    //         ->action('play_game', ['game_id' => $gameId])
    //         ->icon('play')
    //         ->style('success');
    // }

    // /**
    //  * Build a delete button for a game
    //  * 
    //  * @param int $gameId Game ID
    //  * @return \App\Services\UI\Components\ButtonBuilder Button component
    //  */
    // private function buildDeleteButton(int $gameId)
    // {
    //     return UIBuilder::button("delete_{$gameId}_game")
    //         ->label(t('delete_game_action'))
    //         ->action('delete_game', ['game_id' => $gameId])
    //         ->icon('trash')
    //         ->style('danger');
    // }

    /**
     * Get the expected response structure (useful for validation/testing)
     * 
     * @return array
     */
    public static function getResponseStructure(): array
    {
        return GameLobbyScreenStructure::response();
    }
}
